### PR TITLE
Add CSS pack tag

### PR DESCRIPTION
**Pull request by mrkrlli**
@patbenatar @ashwinv11 

- This was missing and causing issues with webpacker in production. The extracted CSS was not getting output anywhere.
- https://github.com/rails/webpacker/blob/master/docs/assets.md#import-from-node-modules

### CODE REVIEW

**Comment by ashwinv11** [comment]
@mrkrlli Nice! we used to have an option to skip webpacker when generating a new app. Can we omit the extra css partial if we're skipping webpacker? Since `stylesheet_pack_tag ` will probably return undefined method? Thanks!!

**Comment by mrkrlli** [comment]
@ashwinv11 Made some updates. If the `webpack` option is passed in, then we replace the `javascript_include_tag` with `javascript_pack_tag` and `stylesheet_pack_tag`. This only happens with the `webpack` flag.

**Comment by mrkrlli** [comment]
I also updated the bundler version to version 2. Running philsophies suspenders w/ the bunlder version was giving me errors before.

**Comment by ashwinv11** [comment]
LGTM! :shipit:

**Pull request merged**
