### PR TITLE
Remove high_voltage

### LINKED ISSUE #43: Remove high_voltage
Suggested by @taboularasa. Do we need this by default?

### PR DESCRIPTION
**Pull request by lexi-lambda**
closes #43

### CODE REVIEW

**Comment by patbenatar** [comment]
What a doozie :-P :shipit:

**Comment by patbenatar** [comment]
Actually before you merge can you double check that suspenders doesn't git keep a directory for app/views/pages or anything related like that?

**Comment by lexi-lambda** [comment]
Oops, sorry, I just merged this, and it looks like it does. I'll remove that in another commit.

**Comment by lexi-lambda** [comment]
@patbenatar Should all be okay now.

**Pull request merged**
