### PR TITLE
Make github repo private

### PR DESCRIPTION
**Pull request by patbenatar**

### CODE REVIEW

**Comment by patbenatar** [comment]
@jdwolk :eyes: por favor

**Comment by jdwolk** [comment]
@patbenatar not sure why we need to paginate?

Still, :shipit:

**Comment by jdwolk** [comment]
Ah nvm I get it, the `-p` is for the `hub create` command, not at the `hub` level, so it's setting the repo as private. Gotcha :thumbsup:

:ship: that thang

**Comment by patbenatar** [comment]
:+1:

**Pull request merged**
