### PR TITLE
Explicitly include spec_helper in rails_helper and remove .rspec

### LINKED ISSUE #84: How does spec_helper get included in rails_helper?
As far as I can tell, right now the answer seems to be "it doesn't". Even so, sometimes it seems to be loaded, but I can't figure out why or how.

Shouldn't there be an explicit `require 'spec_helper'`?

### PR DESCRIPTION
**Pull request by lexi-lambda**
fixes #84

### CODE REVIEW

**Comment by taboularasa** [comment]
@lexi-lambda where is `.rspec` being generated from? is there a way to just not make that file in the first place?

**Comment by lexi-lambda** [comment]
@taboularasa It comes from `rails new`, so probably not.

**Comment by lexi-lambda** [comment]
Er, not `rails new`, `rails g rspec:install`. Either way, it's probably not going to be possible to disable that.

**Comment by taboularasa** [comment]
:shipit:

**Pull request merged**
