### PR TITLE
Move DoD from README into a PR template

### PR DESCRIPTION
**Pull request by patbenatar**
@jdwolk thoughts on this?

### CODE REVIEW

**Comment by jdwolk** [comment]
Is the intent to make it more modular per-project?

**Comment by patbenatar** [comment]
@jdwolk I don't think this changes that.. the template copy can still be modified whether they're in the README or another md file. My goal here was to re-enforce the checklist in the README by bringing it front and center in every PR.

**Comment by patbenatar** [comment]
@jdwolk ping

**Comment by jdwolk** [comment]
@patbenatar :shipit:

**Pull request merged**
