### PR TITLE
Bump Ruby to 2.3.1

### PR DESCRIPTION
**Pull request by ebramanti**
This PR bumps Suspenders to the latest version of Ruby, 2.3.1.

### CODE REVIEW

**Comment by taboularasa** [comment]
@jadengore wat? you're going to have to come in so we can go over this PR in person

**Comment by patbenatar** [comment]
Thanks @jadengore ! What are you using Rails for?

**Comment by ebramanti** [comment]
@patbenatar Rewriting my recipe app in Rails! Think I will be able to build much faster than I was, and it should help me keep myself sharp with Ruby. Tried to run Suspenders on Ruby 2.3.1 and it blew up 😢 

@taboularasa Too late already 🚢ped!!!

**Comment by patbenatar** [comment]
@jadengore awesome!

**Pull request merged**
